# Generated by Django 6.0.2 on 2026-07-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_contactmessage_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='industry',
            field=models.CharField(choices=[('hospitality', 'Ospitalitate'), ('ecommerce', 'E-commerce'), ('service_business', 'Afacere bazată pe programări'), ('saas', 'SaaS / Tehnologie'), ('other', 'Altceva')], max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 stea'), (2, '2 stele'), (3, '3 stele'), (4, '4 stele'), (5, '5 stele')]),
        ),
    ]
