# Generated by Django 6.0.2 on 2026-07-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_contactmessage_industry_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='industry',
            field=models.CharField(choices=[('hospitality', 'Restaurant'), ('service_business', 'Afacere bazată pe programări')], max_length=50),
        ),
    ]
