# Generated by Django 6.0.2 on 2026-08-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_contactmessage_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='industry',
            field=models.CharField(choices=[('hospitality', 'Restaurant'), ('service_business', 'Appointment-based business')], max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')]),
        ),
    ]
