# Generated by Django 6.0.2 on 2026-08-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='credential_url',
            field=models.URLField(blank=True, help_text='Link de verificare a certificatului (opțional).'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='deadline_communication',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='hosting_info',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='industry',
            field=models.CharField(help_text='Domeniul afacerii (liber, ex. restaurant, clinică, consultanță).', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='project_description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='contactmessagesimple',
            name='message',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text='Separă tehnologiile prin virgulă. Exemplu: Django, PostgreSQL, Redis', max_length=300),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 stea'), (2, '2 stele'), (3, '3 stele'), (4, '4 stele'), (5, '5 stele')]),
        ),
    ]
