# Generated by Django 6.0.2 on 2026-08-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_contactmessage_selected_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='selected_package',
            field=models.CharField(blank=True, choices=[('digital_presence', 'Digital Presence — €150'), ('full_experience', 'Full Experience — €380'), ('premium_system', 'Premium System — de la €850'), ('automation_only', 'Doar automatizare / agent AI (am deja un website)'), ('not_sure', 'Nu sunt sigur/ă, hai să discutăm')], help_text='Pachetul ales de pe homepage, dacă a venit de acolo.', max_length=30),
        ),
    ]
