# Generated by Django 6.1 on 2026-08-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_project_result_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='selected_package',
            field=models.CharField(blank=True, choices=[('digital_presence', 'Prezență Digitală — €150'), ('full_experience', 'Experiența Completă — €380'), ('premium_system', 'Sistem Premium — de la €850'), ('automation_only', 'Doar automatizare / agent AI (am deja un website)'), ('not_sure', 'Nu sunt sigur/ă, hai să discutăm')], help_text='Pachetul ales de pe homepage, dacă a venit de acolo.', max_length=30),
        ),
    ]
