# Generated by Django 6.1 on 2026-08-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_contactmessage_selected_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='business_url',
            field=models.URLField(blank=True, help_text='Site-ul afacerii, ca vizitatorii sa poata verifica.'),
        ),
        migrations.AddField(
            model_name='review',
            name='project_note',
            field=models.CharField(blank=True, help_text='Ce s-a construit, pe scurt.', max_length=200),
        ),
        migrations.AddField(
            model_name='review',
            name='role',
            field=models.CharField(blank=True, help_text='Ex: Fondator, Manager.', max_length=120),
        ),
    ]
