# Generated by Django 6.0.2 on 2026-09-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0018_review_business_url_review_project_note_review_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="selected_package",
            field=models.CharField(
                blank=True,
                choices=[
                    ("digital_presence", "Prezență Digitală — €150"),
                    ("full_experience", "Experiență Completă — €380"),
                    ("premium_system", "Sistem Premium — de la €850"),
                    (
                        "automation_only",
                        "Doar automatizare / agent AI (am deja un website)",
                    ),
                    ("not_sure", "Nu sunt sigur/ă, hai să discutăm"),
                ],
                help_text="Pachetul ales de pe homepage, dacă a venit de acolo.",
                max_length=30,
            ),
        ),
    ]
